# Generated by Django 5.2.13 on 2026-04-10 02:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_type', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below')], max_length=12)),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=20)),
                ('notify_enabled', models.BooleanField(default=True)),
                ('auto_trade_enabled', models.BooleanField(default=False)),
                ('auto_trade_side', models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, null=True)),
                ('auto_trade_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_trade_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('paused', 'Paused')], default='active', max_length=10)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='markets.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('notification_only', 'Notification Only'), ('notification_and_trade_executed', 'Notification And Trade Executed'), ('notification_and_trade_skipped', 'Notification And Trade Skipped'), ('notification_and_trade_failed', 'Notification And Trade Failed'), ('trade_executed', 'Trade Executed'), ('trade_skipped', 'Trade Skipped'), ('trade_failed', 'Trade Failed')], max_length=35)),
                ('details', models.JSONField(default=dict)),
                ('notification_sent', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='alerts.alert')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.trade')),
            ],
            options={
                'db_table': 'alert_triggers',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['portfolio', 'status'], name='alerts_portfol_5f8507_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['asset', 'status'], name='alerts_asset_i_a5ee48_idx'),
        ),
    ]
