# Generated by Django 5.2.13 on 2026-04-10 02:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=10)),
                ('fee_rate', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('iana_timezone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'market_configs',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('figi', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('display_symbol', models.CharField(max_length=50)),
                ('provider_symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=5)),
                ('exchange', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('is_seeded', models.BooleanField(default=False)),
                ('last_symbol_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assets',
                'indexes': [models.Index(fields=['market', 'display_symbol'], name='assets_market_f5ab2e_idx')],
                'unique_together': {('market', 'display_symbol')},
            },
        ),
        migrations.CreateModel(
            name='AssetQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('source', models.CharField(default='yahoo_finance', max_length=50)),
                ('as_of', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_delayed', models.BooleanField(default=True)),
                ('provider_payload', models.JSONField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='markets.asset')),
            ],
            options={
                'db_table': 'asset_quotes',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['asset', '-fetched_at'], name='asset_quote_asset_i_09e7b6_idx')],
            },
        ),
    ]
