# Generated by Django 5.2.13 on 2026-04-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetquote',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
    ]
