# Generated by Django 5.2.13 on 2026-04-13 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_assetquote_is_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('source', models.CharField(default='yahoo_finance', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv_data', to='markets.asset')),
            ],
            options={
                'db_table': 'ohlcv',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['asset', '-date'], name='ohlcv_asset_i_c8f870_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('rsi_14', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('macd_histogram', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('ma_20', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('ma_50', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('ma_200', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume_20d_avg', models.BigIntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_indicators', to='markets.asset')),
            ],
            options={
                'db_table': 'technical_indicators',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['asset', '-date'], name='technical_i_asset_i_0f74b3_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
