# Generated by Django 5.2.13 on 2026-04-13 13:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aicost',
            new_name='ai_costs_ai_auth_15cf95_idx',
            old_name='ai_costs_ai_auth_id_created_at_idx',
        ),
        migrations.AlterField(
            model_name='aiauth',
            name='monthly_budget_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Monthly budget in USD for AI calls', max_digits=8),
        ),
    ]
