# Generated by Django 5.2.13 on 2026-04-10 02:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('average_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='markets.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'positions',
                'indexes': [models.Index(fields=['portfolio'], name='positions_portfol_09dad9_idx')],
                'unique_together': {('portfolio', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('gross_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('net_cash_impact', models.DecimalField(decimal_places=2, max_digits=20)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rationale', models.CharField(default='Manual operation', max_length=255)),
                ('executed_by', models.CharField(choices=[('manual', 'Manual'), ('alert', 'Alert'), ('autonomous', 'Autonomous'), ('agent', 'Agent')], default='manual', max_length=12)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='markets.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['portfolio', '-executed_at'], name='trades_portfol_9453b7_idx')],
            },
        ),
    ]
