SEED_ASSETS = {
    "BR": [
        {"display_symbol": "PETR3", "provider_symbol": "PETR3.SA", "name": "Petrobras PN", "exchange": "BVMF", "currency": "BRL", "sector": "Energy"},
        {"display_symbol": "PETR4", "provider_symbol": "PETR4.SA", "name": "Petrobras ON", "exchange": "BVMF", "currency": "BRL", "sector": "Energy"},
        {"display_symbol": "VALE3", "provider_symbol": "VALE3.SA", "name": "Vale ON", "exchange": "BVMF", "currency": "BRL", "sector": "Basic Materials"},
        {"display_symbol": "ITUB4", "provider_symbol": "ITUB4.SA", "name": "Itau Unibanco PN", "exchange": "BVMF", "currency": "BRL", "sector": "Financial"},
        {"display_symbol": "BBDC4", "provider_symbol": "BBDC4.SA", "name": "Bradesco PN", "exchange": "BVMF", "currency": "BRL", "sector": "Financial"},
        {"display_symbol": "ABEV3", "provider_symbol": "ABEV3.SA", "name": "Ambev ON", "exchange": "BVMF", "currency": "BRL", "sector": "Consumer Staples"},
        {"display_symbol": "WEGE3", "provider_symbol": "WEGE3.SA", "name": "WEG ON", "exchange": "BVMF", "currency": "BRL", "sector": "Industrials"},
        {"display_symbol": "MGLU3", "provider_symbol": "MGLU3.SA", "name": "Magazine Luiza ON", "exchange": "BVMF", "currency": "BRL", "sector": "Retail"},
        {"display_symbol": "BBAS3", "provider_symbol": "BBAS3.SA", "name": "Banco do Brasil ON", "exchange": "BVMF", "currency": "BRL", "sector": "Financial"},
        {"display_symbol": "RENT3", "provider_symbol": "RENT3.SA", "name": "Localiza ON", "exchange": "BVMF", "currency": "BRL", "sector": "Industrials"},
        {"display_symbol": "SUOB3", "provider_symbol": "SUOB3.SA", "name": "Sul America ON", "exchange": "BVMF", "currency": "BRL", "sector": "Financial"},
        {"display_symbol": "ELET3", "provider_symbol": "ELET3.SA", "name": "Eletrobras ON", "exchange": "BVMF", "currency": "BRL", "sector": "Utilities"},
        {"display_symbol": "ELET6", "provider_symbol": "ELET6.SA", "name": "Eletrobras PNB", "exchange": "BVMF", "currency": "BRL", "sector": "Utilities"},
        {"display_symbol": "B3SA3", "provider_symbol": "B3SA3.SA", "name": "B3 ON", "exchange": "BVMF", "currency": "BRL", "sector": "Financial"},
        {"display_symbol": "JBSS3", "provider_symbol": "JBSS3.SA", "name": "JBS ON", "exchange": "BVMF", "currency": "BRL", "sector": "Consumer Staples"},
        {"display_symbol": "CSAN3", "provider_symbol": "CSAN3.SA", "name": "Cosan ON", "exchange": "BVMF", "currency": "BRL", "sector": "Energy"},
        {"display_symbol": "RADL3", "provider_symbol": "RADL3.SA", "name": "Raia Droasil ON", "exchange": "BVMF", "currency": "BRL", "sector": "Healthcare"},
        {"display_symbol": "HAPV3", "provider_symbol": "HAPV3.SA", "name": "Hapvida ON", "exchange": "BVMF", "currency": "BRL", "sector": "Healthcare"},
        {"display_symbol": "EQTL3", "provider_symbol": "EQTL3.SA", "name": "Equatorial ON", "exchange": "BVMF", "currency": "BRL", "sector": "Utilities"},
        {"display_symbol": "TAEE11", "provider_symbol": "TAEE11.SA", "name": "Taesa UNT", "exchange": "BVMF", "currency": "BRL", "sector": "Utilities"},
    ],
    "US": [
        {"display_symbol": "AAPL", "provider_symbol": "AAPL", "name": "Apple Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Technology"},
        {"display_symbol": "MSFT", "provider_symbol": "MSFT", "name": "Microsoft Corp.", "exchange": "XNYS", "currency": "USD", "sector": "Technology"},
        {"display_symbol": "GOOGL", "provider_symbol": "GOOGL", "name": "Alphabet Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Technology"},
        {"display_symbol": "AMZN", "provider_symbol": "AMZN", "name": "Amazon.com Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Consumer Discretionary"},
        {"display_symbol": "TSLA", "provider_symbol": "TSLA", "name": "Tesla Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Consumer Discretionary"},
        {"display_symbol": "NVDA", "provider_symbol": "NVDA", "name": "NVIDIA Corp.", "exchange": "XNYS", "currency": "USD", "sector": "Technology"},
        {"display_symbol": "META", "provider_symbol": "META", "name": "Meta Platforms Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Technology"},
        {"display_symbol": "JPM", "provider_symbol": "JPM", "name": "JPMorgan Chase & Co.", "exchange": "XNYS", "currency": "USD", "sector": "Financial"},
        {"display_symbol": "V", "provider_symbol": "V", "name": "Visa Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Financial"},
        {"display_symbol": "JNJ", "provider_symbol": "JNJ", "name": "Johnson & Johnson", "exchange": "XNYS", "currency": "USD", "sector": "Healthcare"},
        {"display_symbol": "WMT", "provider_symbol": "WMT", "name": "Walmart Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Consumer Staples"},
        {"display_symbol": "PG", "provider_symbol": "PG", "name": "Procter & Gamble Co.", "exchange": "XNYS", "currency": "USD", "sector": "Consumer Staples"},
        {"display_symbol": "MA", "provider_symbol": "MA", "name": "Mastercard Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Financial"},
        {"display_symbol": "HD", "provider_symbol": "HD", "name": "Home Depot Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Consumer Discretionary"},
        {"display_symbol": "UNH", "provider_symbol": "UNH", "name": "UnitedHealth Group", "exchange": "XNYS", "currency": "USD", "sector": "Healthcare"},
        {"display_symbol": "DIS", "provider_symbol": "DIS", "name": "Walt Disney Co.", "exchange": "XNYS", "currency": "USD", "sector": "Communication Services"},
        {"display_symbol": "NFLX", "provider_symbol": "NFLX", "name": "Netflix Inc.", "exchange": "XNYS", "currency": "USD", "sector": "Communication Services"},
        {"display_symbol": "BA", "provider_symbol": "BA", "name": "Boeing Co.", "exchange": "XNYS", "currency": "USD", "sector": "Industrials"},
        {"display_symbol": "XOM", "provider_symbol": "XOM", "name": "Exxon Mobil Corp.", "exchange": "XNYS", "currency": "USD", "sector": "Energy"},
        {"display_symbol": "KO", "provider_symbol": "KO", "name": "Coca-Cola Co.", "exchange": "XNYS", "currency": "USD", "sector": "Consumer Staples"},
    ],
    "UK": [
        {"display_symbol": "SHEL", "provider_symbol": "SHEL.L", "name": "Shell plc", "exchange": "XLON", "currency": "GBP", "sector": "Energy"},
        {"display_symbol": "AZN", "provider_symbol": "AZN.L", "name": "AstraZeneca plc", "exchange": "XLON", "currency": "GBP", "sector": "Healthcare"},
        {"display_symbol": "HSBA", "provider_symbol": "HSBA.L", "name": "HSBC Holdings plc", "exchange": "XLON", "currency": "GBP", "sector": "Financial"},
        {"display_symbol": "BP", "provider_symbol": "BP.L", "name": "BP plc", "exchange": "XLON", "currency": "GBP", "sector": "Energy"},
        {"display_symbol": "ULVR", "provider_symbol": "ULVR.L", "name": "Unilever plc", "exchange": "XLON", "currency": "GBP", "sector": "Consumer Staples"},
        {"display_symbol": "GSK", "provider_symbol": "GSK.L", "name": "GSK plc", "exchange": "XLON", "currency": "GBP", "sector": "Healthcare"},
        {"display_symbol": "RIO", "provider_symbol": "RIO.L", "name": "Rio Tinto plc", "exchange": "XLON", "currency": "GBP", "sector": "Basic Materials"},
        {"display_symbol": "BT.A", "provider_symbol": "BT-A.L", "name": "BT Group plc", "exchange": "XLON", "currency": "GBP", "sector": "Communication Services"},
        {"display_symbol": "LLOY", "provider_symbol": "LLOY.L", "name": "Lloyds Banking Group", "exchange": "XLON", "currency": "GBP", "sector": "Financial"},
        {"display_symbol": "BARC", "provider_symbol": "BARC.L", "name": "Barclays plc", "exchange": "XLON", "currency": "GBP", "sector": "Financial"},
        {"display_symbol": "DGE", "provider_symbol": "DGE.L", "name": "Diageo plc", "exchange": "XLON", "currency": "GBP", "sector": "Consumer Staples"},
        {"display_symbol": "NG", "provider_symbol": "NG.L", "name": "National Grid plc", "exchange": "XLON", "currency": "GBP", "sector": "Utilities"},
        {"display_symbol": "REL", "provider_symbol": "REL.L", "name": "Relx plc", "exchange": "XLON", "currency": "GBP", "sector": "Technology"},
        {"display_symbol": "PRU", "provider_symbol": "PRU.L", "name": "Prudential plc", "exchange": "XLON", "currency": "GBP", "sector": "Financial"},
        {"display_symbol": "CRH", "provider_symbol": "CRH.L", "name": "CRH plc", "exchange": "XLON", "currency": "GBP", "sector": "Basic Materials"},
        {"display_symbol": "SVT", "provider_symbol": "SVT.L", "name": "Severn Trent plc", "exchange": "XLON", "currency": "GBP", "sector": "Utilities"},
        {"display_symbol": "TW.", "provider_symbol": "TW.L", "name": "Taylor Wimpey plc", "exchange": "XLON", "currency": "GBP", "sector": "Consumer Discretionary"},
        {"display_symbol": "AVST", "provider_symbol": "AVST.L", "name": "Avast plc", "exchange": "XLON", "currency": "GBP", "sector": "Technology"},
        {"display_symbol": "ITV", "provider_symbol": "ITV.L", "name": "ITV plc", "exchange": "XLON", "currency": "GBP", "sector": "Communication Services"},
        {"display_symbol": "CCH", "provider_symbol": "CCH.L", "name": "Coca-Cola HBC AG", "exchange": "XLON", "currency": "GBP", "sector": "Consumer Staples"},
    ],
    "EU": [
        {"display_symbol": "MC", "provider_symbol": "MC.PA", "name": "LVMH Moet Hennessy Louis Vuitton", "exchange": "XPAR", "currency": "EUR", "sector": "Consumer Discretionary"},
        {"display_symbol": "OR", "provider_symbol": "OR.PA", "name": "L'Oreal SA", "exchange": "XPAR", "currency": "EUR", "sector": "Consumer Staples"},
        {"display_symbol": "SAP", "provider_symbol": "SAP.DE", "name": "SAP SE", "exchange": "XPAR", "currency": "EUR", "sector": "Technology"},
        {"display_symbol": "ASML", "provider_symbol": "ASML.AS", "name": "ASML Holding NV", "exchange": "XPAR", "currency": "EUR", "sector": "Technology"},
        {"display_symbol": "SAN", "provider_symbol": "SAN.PA", "name": "Sanofi SA", "exchange": "XPAR", "currency": "EUR", "sector": "Healthcare"},
        {"display_symbol": "SIE", "provider_symbol": "SIE.DE", "name": "Siemens AG", "exchange": "XPAR", "currency": "EUR", "sector": "Industrials"},
        {"display_symbol": "ALV", "provider_symbol": "ALV.DE", "name": "Allianz SE", "exchange": "XPAR", "currency": "EUR", "sector": "Financial"},
        {"display_symbol": "DTE", "provider_symbol": "DTE.DE", "name": "Deutsche Telekom AG", "exchange": "XPAR", "currency": "EUR", "sector": "Communication Services"},
        {"display_symbol": "TOT", "provider_symbol": "TTE.PA", "name": "TotalEnergies SE", "exchange": "XPAR", "currency": "EUR", "sector": "Energy"},
        {"display_symbol": "AIR", "provider_symbol": "AIR.PA", "name": "Airbus SE", "exchange": "XPAR", "currency": "EUR", "sector": "Industrials"},
        {"display_symbol": "BN", "provider_symbol": "BN.PA", "name": "Danone SA", "exchange": "XPAR", "currency": "EUR", "sector": "Consumer Staples"},
        {"display_symbol": "SU", "provider_symbol": "SU.PA", "name": "Schneider Electric SE", "exchange": "XPAR", "currency": "EUR", "sector": "Industrials"},
        {"display_symbol": "ENEL", "provider_symbol": "ENEL.MI", "name": "Enel SpA", "exchange": "XPAR", "currency": "EUR", "sector": "Utilities"},
        {"display_symbol": "ENI", "provider_symbol": "ENI.MI", "name": "Eni SpA", "exchange": "XPAR", "currency": "EUR", "sector": "Energy"},
        {"display_symbol": "ISP", "provider_symbol": "ISP.MI", "name": "Intesa Sanpaolo SpA", "exchange": "XPAR", "currency": "EUR", "sector": "Financial"},
        {"display_symbol": "BAS", "provider_symbol": "BAS.DE", "name": "BASF SE", "exchange": "XPAR", "currency": "EUR", "sector": "Basic Materials"},
        {"display_symbol": "BMW", "provider_symbol": "BMW.DE", "name": "Bayerische Motoren Werke AG", "exchange": "XPAR", "currency": "EUR", "sector": "Consumer Discretionary"},
        {"display_symbol": "ADS", "provider_symbol": "ADS.DE", "name": "Adidas AG", "exchange": "XPAR", "currency": "EUR", "sector": "Consumer Discretionary"},
        {"display_symbol": "VOW3", "provider_symbol": "VOW3.DE", "name": "Volkswagen AG Vz.", "exchange": "XPAR", "currency": "EUR", "sector": "Consumer Discretionary"},
        {"display_symbol": "IFX", "provider_symbol": "IFX.DE", "name": "Infineon Technologies AG", "exchange": "XPAR", "currency": "EUR", "sector": "Technology"},
    ],
}


def run_seed():
    from markets.services import get_or_create_asset

    for market, assets in SEED_ASSETS.items():
        for asset_data in assets:
            get_or_create_asset(
                display_symbol=asset_data["display_symbol"],
                market=market,
                provider_symbol=asset_data["provider_symbol"],
                name=asset_data["name"],
                exchange=asset_data["exchange"],
                currency=asset_data["currency"],
                sector=asset_data.get("sector", ""),
                industry=asset_data.get("industry", ""),
                is_seeded=True,
            )