# Generated by Django 5.2.13 on 2026-04-10 02:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('trade', 'Trade'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('alert_triggered', 'Alert Triggered'), ('alert_notification', 'Alert Notification')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'timeline_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='timeline_ev_portfol_942db0_idx')],
            },
        ),
    ]
