# Generated by Django 5.2.13 on 2026-04-13 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0003_portfolio_is_simulating'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('rsi_oversold', 'RSI Oversold/Overbought'), ('ma_crossover', 'Moving Average Crossover'), ('macd_crossover', 'MACD Crossover'), ('bb_bands', 'Bollinger Bands'), ('combination', 'Combination (AND)')], max_length=20)),
                ('description', models.TextField()),
                ('conditions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategy_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategyInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('backtest_approved_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='portfolios.portfolio')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategyrule')),
            ],
            options={
                'db_table': 'strategy_instances',
                'ordering': ['-created_at'],
                'unique_together': {('portfolio', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='BacktestScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('strategy_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_scenarios', to='strategies.strategyinstance')),
            ],
            options={
                'db_table': 'backtest_scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField()),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('executed_at', models.DateTimeField()),
                ('auto_executed', models.BooleanField(default=False)),
                ('matched_conditions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='strategies.strategyinstance')),
            ],
            options={
                'db_table': 'strategy_trades',
                'ordering': ['-executed_at'],
            },
        ),
    ]
