# Generated by Django 5.2.13 on 2026-04-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otp',
            new_name='mcp_otps_user_id_3b8518_idx',
            old_name='mcp_otps_user_id_code_idx',
        ),
    ]
