# Generated by Django 5.2.13 on 2026-04-10 02:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=5)),
                ('base_currency', models.CharField(editable=False, max_length=3)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('current_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('initial_funding', 'Initial Funding'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('resulting_cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'cash_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('positions_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_equity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('net_external_cash_flows', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'portfolio_snapshots',
                'ordering': ['-captured_at'],
            },
        ),
    ]
