# Generated by Django 5.2.13 on 2026-04-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_cash_transaction_initiated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_simulating',
            field=models.BooleanField(default=False),
        ),
    ]
