# Generated by Codex on 2026-04-16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0004_portfolioguardrails"),
        ("markets", "0004_newsitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioWatchMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_watch_memberships",
                        to="markets.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_memberships",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_watch_memberships",
                "ordering": ["-created_at"],
                "unique_together": {("portfolio", "asset")},
                "indexes": [models.Index(fields=["portfolio"], name="portfoliowat_portfolio_idx")],
            },
        ),
    ]
